[project]
name = "manim-physics"
version = "0.4.0"
description = "Support physics simulation"
readme = "README.md"
requires-python = ">=3.9"
authors = [
  { name = "Matheart", email = "waautomationwong@gmail.com" }
]

dependencies = [
  "manim",
  "pymunk",
  "shapely",
]
